# Generated by Django 4.2 on 2023-05-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lon", models.DecimalField(decimal_places=6, max_digits=9)),
                ("timezone", models.CharField(max_length=100)),
                ("timezone_offset", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HourlyWeather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField()),
                ("temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("feels_like", models.DecimalField(decimal_places=2, max_digits=5)),
                ("pressure", models.DecimalField(decimal_places=2, max_digits=6)),
                ("humidity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("dew_point", models.DecimalField(decimal_places=2, max_digits=5)),
                ("clouds", models.DecimalField(decimal_places=2, max_digits=5)),
                ("uvi", models.DecimalField(decimal_places=2, max_digits=5)),
                ("visibility", models.DecimalField(decimal_places=2, max_digits=6)),
                ("wind_speed", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "wind_gust",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("wind_deg", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "rain_1h",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "snow_1h",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("pop", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weather_id", models.IntegerField()),
                ("weather_main", models.CharField(max_length=100)),
                ("weather_description", models.CharField(max_length=100)),
                ("weather_icon", models.CharField(max_length=50)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wheater.city"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyWeather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField()),
                ("temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("feels_like", models.DecimalField(decimal_places=2, max_digits=5)),
                ("pressure", models.DecimalField(decimal_places=2, max_digits=6)),
                ("humidity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("dew_point", models.DecimalField(decimal_places=2, max_digits=5)),
                ("clouds", models.DecimalField(decimal_places=2, max_digits=5)),
                ("uvi", models.DecimalField(decimal_places=2, max_digits=5)),
                ("visibility", models.DecimalField(decimal_places=2, max_digits=6)),
                ("wind_speed", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "wind_gust",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("wind_deg", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "rain_1h",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "snow_1h",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("sunrise", models.DateTimeField()),
                ("sunset", models.DateTimeField()),
                ("moonrise", models.DateTimeField()),
                ("moonset", models.DateTimeField()),
                ("moon_phase", models.DecimalField(decimal_places=2, max_digits=3)),
                ("temp_morn", models.DecimalField(decimal_places=2, max_digits=5)),
                ("temp_day", models.DecimalField(decimal_places=2, max_digits=5)),
                ("temp_eve", models.DecimalField(decimal_places=2, max_digits=5)),
                ("temp_night", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "feels_like_morn",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("feels_like_day", models.DecimalField(decimal_places=2, max_digits=5)),
                ("feels_like_eve", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "feels_like_night",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("pop", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "rain",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "snow",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wheater.city"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CurrentWeather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField()),
                ("temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("feels_like", models.DecimalField(decimal_places=2, max_digits=5)),
                ("pressure", models.DecimalField(decimal_places=2, max_digits=6)),
                ("humidity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("dew_point", models.DecimalField(decimal_places=2, max_digits=5)),
                ("clouds", models.DecimalField(decimal_places=2, max_digits=5)),
                ("uvi", models.DecimalField(decimal_places=2, max_digits=5)),
                ("visibility", models.DecimalField(decimal_places=2, max_digits=6)),
                ("wind_speed", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "wind_gust",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("wind_deg", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "rain_1h",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "snow_1h",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wheater.city"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
