# Generated by Django 4.2 on 2023-05-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wheater", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="currentweather",
            name="dt",
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name="dailyweather",
            name="dt",
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name="hourlyweather",
            name="dt",
            field=models.DateTimeField(unique=True),
        ),
    ]
