# Generated by Django 4.2 on 2023-05-10 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_favoritecity_user_favorite_cities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favoritecity",
            name="city",
        ),
        migrations.RemoveField(
            model_name="favoritecity",
            name="user",
        ),
    ]
