# Generated by Django 4.2 on 2023-05-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userinteraction", "0001_initial"),
        ("user", "0005_remove_favoritecity_city_remove_favoritecity_user"),
        ("wheater", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favorite_cities",
            field=models.ManyToManyField(
                related_name="users_favorite",
                through="userinteraction.FavoriteCity",
                to="wheater.city",
            ),
        ),
        migrations.DeleteModel(
            name="FavoriteCity",
        ),
    ]
