# Generated by Django 4.2 on 2023-05-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_user_favorite_cities_delete_favoritecity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification",
            field=models.BooleanField(default=True, verbose_name="notification"),
        ),
    ]
