# Generated by Django 4.2 on 2023-05-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_user_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notification",
            field=models.BooleanField(default=False, verbose_name="notification"),
        ),
    ]
